[advisories]
ignore = []
yanked = "deny"
unmaintained = "all"

[bans]
multiple-versions = "warn"
wildcards = "deny"


skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016"
]

confidence-threshold = 0.8
